version: '3'
services:
    mysql:
        image: mysql:5.7
        container_name: ng-mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
    php:
        build: .
        container_name: ng-php
        ports:
            - 80:80
        links: 
            - mysql:mysql
        volumes:
            - /home/thebest/Desktop/Projects/laravel/html:/var/www/html
